/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package baber;

/**
 *
 * @author USER
 */
import backend.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.DefaultListModel;
public class FrmStruck extends javax.swing.JFrame {

    /**
     * Creates new form FrmStruck
     */
    public FrmStruck() {
        initComponents();
        tampilkanDataCustomer();
        tampilkanDataAppointment();
        tampilkanDataService();
        
    }
    
    public void tampilkanDataCustomer(){
        String[] kolom = {"ID", "Firstname", "Lastname","Phone", "Gender", "Address", "id_service"};
        ArrayList<customer> list = new customer().getAll();
        Object rowData[] = new Object[7];
        
        tblCustom.setModel(new DefaultTableModel(new Object[][] {}, kolom));
        
        for(customer cust : list){
            rowData[0] = cust.getId_custom();
            rowData[1] = cust.getFirstname();
            rowData[2] = cust.getLastname();
            rowData[3] = cust.getPhone();
            rowData[4] = cust.getGender();
            rowData[5] = cust.getAddress();
            rowData[6] = cust.getServis().getId_service();
   
            
            ((DefaultTableModel)tblCustom.getModel()).addRow(rowData);
        }
    }
    
    public void tampilkanDataAppointment(){
        String[] kolom = {"ID", "Date", "Time", "Place", "id_custom"};
        ArrayList<appointment> list = new appointment().getAll();
        Object rowData[] = new Object[5];
        
        tblAppoint.setModel(new DefaultTableModel(new Object[][] {}, kolom));
        
        for(appointment app : list){
            rowData[0] = app.getId_appoint();
            rowData[1] = app.getAppointDate();
            rowData[2] = app.getAppointTime();
            rowData[3] = app.getAppointPlace();
            rowData[4] = app.getCust().getId_custom();
            
            
   
            
            ((DefaultTableModel)tblAppoint.getModel()).addRow(rowData);
        }
    }
    
    public void tampilkanDataService(){
        String[] kolom = {"id_service", "Service Name", "Duration","Price"};
        customer cst = new customer();
        FrmCustomer c = new FrmCustomer();
        int ids = cst.getServis().getId_service();
        int clm = tblCustom.getSelectedColumn();
        ArrayList<service> list = new service().getAllByIdList(ids);
        Object rowData[] = new Object[4];
        
        tblService.setModel(new DefaultTableModel(new Object[][] {}, kolom));
        
        for(service serv : list){
            rowData[0] = serv.getId_service();
            rowData[1] = serv.getName();
            rowData[2] = serv.getDuration();
            rowData[3] = serv.getPrice();
            
            
            ((DefaultTableModel)tblService.getModel()).addRow(rowData);
        }
        
        
    }
    
    public void tampilkanDataTabel(){
        String[] kolom = {"ID", "Service Name", "Duration","Price"};
        ArrayList<service> list = new service().getAll();
        Object rowData[] = new Object[4];
        
        tblService.setModel(new DefaultTableModel(new Object[][] {}, kolom));
        
        for(service serv : list){
            
            rowData[0] = serv.getId_service();
            rowData[1] = serv.getName();
            rowData[2] = serv.getDuration();
            rowData[3] = serv.getPrice();

            ((DefaultTableModel)tblService.getModel()).addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustom = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAppoint = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblService = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Label Struck");

        tblCustom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCustom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCustomMouseClicked(evt);
            }
        });
        tblCustom.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tblCustomComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(tblCustom);

        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tblAppoint.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAppoint.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tblAppointComponentShown(evt);
            }
        });
        jScrollPane2.setViewportView(tblAppoint);

        jLabel3.setText("Customer Data");

        jLabel4.setText("Appointment Data");

        tblService.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblService.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tblServiceComponentShown(evt);
            }
        });
        jScrollPane3.setViewportView(tblService);

        jLabel5.setText("Service Data (To see, click your id_service on Customer Data Tabel)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(227, 227, 227)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel3))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel4))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel5))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jButton3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblCustomComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tblCustomComponentShown
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tblCustomComponentShown

    private void tblAppointComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tblAppointComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_tblAppointComponentShown

    private void tblServiceComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tblServiceComponentShown
        // TODO add your handling code here:
        tblService.getSelectedRow();
    }//GEN-LAST:event_tblServiceComponentShown

    private void tblCustomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCustomMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tblCustom.getModel();
        int row = tblCustom.getSelectedRow();
        String[] kolom = {"id_service", "Service Name", "Duration","Price"};
        ArrayList<service> list = new service().getAllByIdList(Integer.valueOf(model.getValueAt(row, 6).toString()));
        Object rowData[] = new Object[4];
        tblService.setModel(new DefaultTableModel(new Object[][] {}, kolom));
        
        for(service serv : list){
            rowData[0] = serv.getId_service();
            rowData[1] = serv.getName();
            rowData[2] = serv.getDuration();
            rowData[3] = serv.getPrice();
            
            
            ((DefaultTableModel)tblService.getModel()).addRow(rowData);
        }
    }//GEN-LAST:event_tblCustomMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new FrmPay().show();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new FrmAppointment().show();
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmStruck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmStruck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmStruck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmStruck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmStruck().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblAppoint;
    private javax.swing.JTable tblCustom;
    private javax.swing.JTable tblService;
    // End of variables declaration//GEN-END:variables
}
