/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Swalayan.GUI;

/**
 *
 * @author Rimuru
 */
public class Home_page extends javax.swing.JFrame {

    /**
     * Creates new form Home_page
     */
    public Home_page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        ButtonBarang = new javax.swing.JButton();
        ButtonMember = new javax.swing.JButton();
        ButtonKaryawan = new javax.swing.JButton();
        ButtonPenjualan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ButtonBarang.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        ButtonBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shopping.png"))); // NOI18N
        ButtonBarang.setText("Barang");
        ButtonBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBarangActionPerformed(evt);
            }
        });

        ButtonMember.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        ButtonMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pool-membership-card.png"))); // NOI18N
        ButtonMember.setText("Member");
        ButtonMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMemberActionPerformed(evt);
            }
        });

        ButtonKaryawan.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        ButtonKaryawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/employees.png"))); // NOI18N
        ButtonKaryawan.setText("Karyawan");
        ButtonKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKaryawanActionPerformed(evt);
            }
        });

        ButtonPenjualan.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        ButtonPenjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shopping-cart.png"))); // NOI18N
        ButtonPenjualan.setText("Penjualan");
        ButtonPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPenjualanActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 50)); // NOI18N
        jLabel1.setText("HOME PAGE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonMember, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonKaryawan)
                            .addComponent(ButtonPenjualan))
                        .addGap(16, 16, 16)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(ButtonKaryawan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonMember)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonPenjualan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonBarang)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBarangActionPerformed
        // TODO add your handling code here:
        Barang Barangtampil = new Barang();
        Barangtampil.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ButtonBarangActionPerformed

    private void ButtonKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKaryawanActionPerformed
        // TODO add your handling code here:
        Karyawan Karyawantampil = new Karyawan();
        Karyawantampil.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ButtonKaryawanActionPerformed

    private void ButtonMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMemberActionPerformed
        // TODO add your handling code here:
        Member Membertampil = new Member();
        Membertampil.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ButtonMemberActionPerformed

    private void ButtonPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPenjualanActionPerformed
        // TODO add your handling code here:
        Penjualan Penjualantampil = new Penjualan();
        Penjualantampil.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ButtonPenjualanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBarang;
    private javax.swing.JButton ButtonKaryawan;
    private javax.swing.JButton ButtonMember;
    private javax.swing.JButton ButtonPenjualan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
